name: Build Zygisk Module

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK 29
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;29.0.14206865"

      - name: Build Module
        run: |
          python build.py -t release zip
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/29.0.14206865

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-module
          path: release/*.zip
